// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	track "github.com/joergmis/track"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetAllCustomers provides a mock function with given fields:
func (_m *MockRepository) GetAllCustomers() ([]track.Customer, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllCustomers")
	}

	var r0 []track.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]track.Customer, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []track.Customer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]track.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetAllCustomers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllCustomers'
type MockRepository_GetAllCustomers_Call struct {
	*mock.Call
}

// GetAllCustomers is a helper method to define mock.On call
func (_e *MockRepository_Expecter) GetAllCustomers() *MockRepository_GetAllCustomers_Call {
	return &MockRepository_GetAllCustomers_Call{Call: _e.mock.On("GetAllCustomers")}
}

func (_c *MockRepository_GetAllCustomers_Call) Run(run func()) *MockRepository_GetAllCustomers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_GetAllCustomers_Call) Return(_a0 []track.Customer, _a1 error) *MockRepository_GetAllCustomers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetAllCustomers_Call) RunAndReturn(run func() ([]track.Customer, error)) *MockRepository_GetAllCustomers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
