// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	track "github.com/joergmis/track"
	mock "github.com/stretchr/testify/mock"
)

// MockBackend is an autogenerated mock type for the Backend type
type MockBackend struct {
	mock.Mock
}

type MockBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackend) EXPECT() *MockBackend_Expecter {
	return &MockBackend_Expecter{mock: &_m.Mock}
}

// AddTimeEntry provides a mock function with given fields: activity
func (_m *MockBackend) AddTimeEntry(activity track.Activity) error {
	ret := _m.Called(activity)

	if len(ret) == 0 {
		panic("no return value specified for AddTimeEntry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(track.Activity) error); ok {
		r0 = rf(activity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBackend_AddTimeEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTimeEntry'
type MockBackend_AddTimeEntry_Call struct {
	*mock.Call
}

// AddTimeEntry is a helper method to define mock.On call
//   - activity track.Activity
func (_e *MockBackend_Expecter) AddTimeEntry(activity interface{}) *MockBackend_AddTimeEntry_Call {
	return &MockBackend_AddTimeEntry_Call{Call: _e.mock.On("AddTimeEntry", activity)}
}

func (_c *MockBackend_AddTimeEntry_Call) Run(run func(activity track.Activity)) *MockBackend_AddTimeEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(track.Activity))
	})
	return _c
}

func (_c *MockBackend_AddTimeEntry_Call) Return(_a0 error) *MockBackend_AddTimeEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBackend_AddTimeEntry_Call) RunAndReturn(run func(track.Activity) error) *MockBackend_AddTimeEntry_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllCustomers provides a mock function with given fields:
func (_m *MockBackend) GetAllCustomers() ([]track.Customer, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllCustomers")
	}

	var r0 []track.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]track.Customer, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []track.Customer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]track.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBackend_GetAllCustomers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllCustomers'
type MockBackend_GetAllCustomers_Call struct {
	*mock.Call
}

// GetAllCustomers is a helper method to define mock.On call
func (_e *MockBackend_Expecter) GetAllCustomers() *MockBackend_GetAllCustomers_Call {
	return &MockBackend_GetAllCustomers_Call{Call: _e.mock.On("GetAllCustomers")}
}

func (_c *MockBackend_GetAllCustomers_Call) Run(run func()) *MockBackend_GetAllCustomers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBackend_GetAllCustomers_Call) Return(_a0 []track.Customer, _a1 error) *MockBackend_GetAllCustomers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBackend_GetAllCustomers_Call) RunAndReturn(run func() ([]track.Customer, error)) *MockBackend_GetAllCustomers_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllServices provides a mock function with given fields:
func (_m *MockBackend) GetAllServices() ([]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllServices")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBackend_GetAllServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllServices'
type MockBackend_GetAllServices_Call struct {
	*mock.Call
}

// GetAllServices is a helper method to define mock.On call
func (_e *MockBackend_Expecter) GetAllServices() *MockBackend_GetAllServices_Call {
	return &MockBackend_GetAllServices_Call{Call: _e.mock.On("GetAllServices")}
}

func (_c *MockBackend_GetAllServices_Call) Run(run func()) *MockBackend_GetAllServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBackend_GetAllServices_Call) Return(_a0 []string, _a1 error) *MockBackend_GetAllServices_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBackend_GetAllServices_Call) RunAndReturn(run func() ([]string, error)) *MockBackend_GetAllServices_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBackend creates a new instance of MockBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackend {
	mock := &MockBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
