// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"

	track "github.com/joergmis/track"
)

// MockProjectRepository is an autogenerated mock type for the ProjectRepository type
type MockProjectRepository struct {
	mock.Mock
}

type MockProjectRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectRepository) EXPECT() *MockProjectRepository_Expecter {
	return &MockProjectRepository_Expecter{mock: &_m.Mock}
}

// GetAllCustomers provides a mock function with given fields:
func (_m *MockProjectRepository) GetAllCustomers() ([]track.Customer, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllCustomers")
	}

	var r0 []track.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]track.Customer, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []track.Customer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]track.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectRepository_GetAllCustomers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllCustomers'
type MockProjectRepository_GetAllCustomers_Call struct {
	*mock.Call
}

// GetAllCustomers is a helper method to define mock.On call
func (_e *MockProjectRepository_Expecter) GetAllCustomers() *MockProjectRepository_GetAllCustomers_Call {
	return &MockProjectRepository_GetAllCustomers_Call{Call: _e.mock.On("GetAllCustomers")}
}

func (_c *MockProjectRepository_GetAllCustomers_Call) Run(run func()) *MockProjectRepository_GetAllCustomers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProjectRepository_GetAllCustomers_Call) Return(_a0 []track.Customer, _a1 error) *MockProjectRepository_GetAllCustomers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectRepository_GetAllCustomers_Call) RunAndReturn(run func() ([]track.Customer, error)) *MockProjectRepository_GetAllCustomers_Call {
	_c.Call.Return(run)
	return _c
}

// GetTimeEntries provides a mock function with given fields: start, end
func (_m *MockProjectRepository) GetTimeEntries(start time.Time, end time.Time) ([]track.Activity, error) {
	ret := _m.Called(start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetTimeEntries")
	}

	var r0 []track.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) ([]track.Activity, error)); ok {
		return rf(start, end)
	}
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) []track.Activity); ok {
		r0 = rf(start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]track.Activity)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time, time.Time) error); ok {
		r1 = rf(start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectRepository_GetTimeEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTimeEntries'
type MockProjectRepository_GetTimeEntries_Call struct {
	*mock.Call
}

// GetTimeEntries is a helper method to define mock.On call
//   - start time.Time
//   - end time.Time
func (_e *MockProjectRepository_Expecter) GetTimeEntries(start interface{}, end interface{}) *MockProjectRepository_GetTimeEntries_Call {
	return &MockProjectRepository_GetTimeEntries_Call{Call: _e.mock.On("GetTimeEntries", start, end)}
}

func (_c *MockProjectRepository_GetTimeEntries_Call) Run(run func(start time.Time, end time.Time)) *MockProjectRepository_GetTimeEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time), args[1].(time.Time))
	})
	return _c
}

func (_c *MockProjectRepository_GetTimeEntries_Call) Return(_a0 []track.Activity, _a1 error) *MockProjectRepository_GetTimeEntries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectRepository_GetTimeEntries_Call) RunAndReturn(run func(time.Time, time.Time) ([]track.Activity, error)) *MockProjectRepository_GetTimeEntries_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProjectRepository creates a new instance of MockProjectRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectRepository {
	mock := &MockProjectRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
