// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	track "github.com/joergmis/track"
	mock "github.com/stretchr/testify/mock"
)

// MockProjectRepository is an autogenerated mock type for the ProjectRepository type
type MockProjectRepository struct {
	mock.Mock
}

type MockProjectRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectRepository) EXPECT() *MockProjectRepository_Expecter {
	return &MockProjectRepository_Expecter{mock: &_m.Mock}
}

// GetAllProjects provides a mock function with given fields:
func (_m *MockProjectRepository) GetAllProjects() ([]track.Project, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllProjects")
	}

	var r0 []track.Project
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]track.Project, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []track.Project); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]track.Project)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectRepository_GetAllProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllProjects'
type MockProjectRepository_GetAllProjects_Call struct {
	*mock.Call
}

// GetAllProjects is a helper method to define mock.On call
func (_e *MockProjectRepository_Expecter) GetAllProjects() *MockProjectRepository_GetAllProjects_Call {
	return &MockProjectRepository_GetAllProjects_Call{Call: _e.mock.On("GetAllProjects")}
}

func (_c *MockProjectRepository_GetAllProjects_Call) Run(run func()) *MockProjectRepository_GetAllProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProjectRepository_GetAllProjects_Call) Return(_a0 []track.Project, _a1 error) *MockProjectRepository_GetAllProjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectRepository_GetAllProjects_Call) RunAndReturn(run func() ([]track.Project, error)) *MockProjectRepository_GetAllProjects_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomerProjects provides a mock function with given fields: customer
func (_m *MockProjectRepository) GetCustomerProjects(customer track.Customer) ([]track.Project, error) {
	ret := _m.Called(customer)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerProjects")
	}

	var r0 []track.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(track.Customer) ([]track.Project, error)); ok {
		return rf(customer)
	}
	if rf, ok := ret.Get(0).(func(track.Customer) []track.Project); ok {
		r0 = rf(customer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]track.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(track.Customer) error); ok {
		r1 = rf(customer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectRepository_GetCustomerProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomerProjects'
type MockProjectRepository_GetCustomerProjects_Call struct {
	*mock.Call
}

// GetCustomerProjects is a helper method to define mock.On call
//   - customer track.Customer
func (_e *MockProjectRepository_Expecter) GetCustomerProjects(customer interface{}) *MockProjectRepository_GetCustomerProjects_Call {
	return &MockProjectRepository_GetCustomerProjects_Call{Call: _e.mock.On("GetCustomerProjects", customer)}
}

func (_c *MockProjectRepository_GetCustomerProjects_Call) Run(run func(customer track.Customer)) *MockProjectRepository_GetCustomerProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(track.Customer))
	})
	return _c
}

func (_c *MockProjectRepository_GetCustomerProjects_Call) Return(_a0 []track.Project, _a1 error) *MockProjectRepository_GetCustomerProjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectRepository_GetCustomerProjects_Call) RunAndReturn(run func(track.Customer) ([]track.Project, error)) *MockProjectRepository_GetCustomerProjects_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProjectRepository creates a new instance of MockProjectRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectRepository {
	mock := &MockProjectRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
