// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	track "github.com/joergmis/track"
	mock "github.com/stretchr/testify/mock"
)

// MockActivityRepository is an autogenerated mock type for the ActivityRepository type
type MockActivityRepository struct {
	mock.Mock
}

type MockActivityRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActivityRepository) EXPECT() *MockActivityRepository_Expecter {
	return &MockActivityRepository_Expecter{mock: &_m.Mock}
}

// GetCurrentActivity provides a mock function with given fields:
func (_m *MockActivityRepository) GetCurrentActivity() (track.Activity, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentActivity")
	}

	var r0 track.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func() (track.Activity, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() track.Activity); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(track.Activity)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockActivityRepository_GetCurrentActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentActivity'
type MockActivityRepository_GetCurrentActivity_Call struct {
	*mock.Call
}

// GetCurrentActivity is a helper method to define mock.On call
func (_e *MockActivityRepository_Expecter) GetCurrentActivity() *MockActivityRepository_GetCurrentActivity_Call {
	return &MockActivityRepository_GetCurrentActivity_Call{Call: _e.mock.On("GetCurrentActivity")}
}

func (_c *MockActivityRepository_GetCurrentActivity_Call) Run(run func()) *MockActivityRepository_GetCurrentActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockActivityRepository_GetCurrentActivity_Call) Return(_a0 track.Activity, _a1 error) *MockActivityRepository_GetCurrentActivity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockActivityRepository_GetCurrentActivity_Call) RunAndReturn(run func() (track.Activity, error)) *MockActivityRepository_GetCurrentActivity_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: _a0
func (_m *MockActivityRepository) Start(_a0 track.Activity) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(track.Activity) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockActivityRepository_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockActivityRepository_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - _a0 track.Activity
func (_e *MockActivityRepository_Expecter) Start(_a0 interface{}) *MockActivityRepository_Start_Call {
	return &MockActivityRepository_Start_Call{Call: _e.mock.On("Start", _a0)}
}

func (_c *MockActivityRepository_Start_Call) Run(run func(_a0 track.Activity)) *MockActivityRepository_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(track.Activity))
	})
	return _c
}

func (_c *MockActivityRepository_Start_Call) Return(_a0 error) *MockActivityRepository_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockActivityRepository_Start_Call) RunAndReturn(run func(track.Activity) error) *MockActivityRepository_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with given fields:
func (_m *MockActivityRepository) Stop() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockActivityRepository_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockActivityRepository_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockActivityRepository_Expecter) Stop() *MockActivityRepository_Stop_Call {
	return &MockActivityRepository_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockActivityRepository_Stop_Call) Run(run func()) *MockActivityRepository_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockActivityRepository_Stop_Call) Return(_a0 error) *MockActivityRepository_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockActivityRepository_Stop_Call) RunAndReturn(run func() error) *MockActivityRepository_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockActivityRepository creates a new instance of MockActivityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActivityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActivityRepository {
	mock := &MockActivityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
