// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	track "github.com/joergmis/track"
	mock "github.com/stretchr/testify/mock"
)

// MockActivityRepository is an autogenerated mock type for the ActivityRepository type
type MockActivityRepository struct {
	mock.Mock
}

type MockActivityRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActivityRepository) EXPECT() *MockActivityRepository_Expecter {
	return &MockActivityRepository_Expecter{mock: &_m.Mock}
}

// AddActivity provides a mock function with given fields: activity
func (_m *MockActivityRepository) AddActivity(activity track.Activity) error {
	ret := _m.Called(activity)

	if len(ret) == 0 {
		panic("no return value specified for AddActivity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(track.Activity) error); ok {
		r0 = rf(activity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockActivityRepository_AddActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddActivity'
type MockActivityRepository_AddActivity_Call struct {
	*mock.Call
}

// AddActivity is a helper method to define mock.On call
//   - activity track.Activity
func (_e *MockActivityRepository_Expecter) AddActivity(activity interface{}) *MockActivityRepository_AddActivity_Call {
	return &MockActivityRepository_AddActivity_Call{Call: _e.mock.On("AddActivity", activity)}
}

func (_c *MockActivityRepository_AddActivity_Call) Run(run func(activity track.Activity)) *MockActivityRepository_AddActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(track.Activity))
	})
	return _c
}

func (_c *MockActivityRepository_AddActivity_Call) Return(_a0 error) *MockActivityRepository_AddActivity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockActivityRepository_AddActivity_Call) RunAndReturn(run func(track.Activity) error) *MockActivityRepository_AddActivity_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteActivity provides a mock function with given fields: activity
func (_m *MockActivityRepository) DeleteActivity(activity track.Activity) error {
	ret := _m.Called(activity)

	if len(ret) == 0 {
		panic("no return value specified for DeleteActivity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(track.Activity) error); ok {
		r0 = rf(activity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockActivityRepository_DeleteActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteActivity'
type MockActivityRepository_DeleteActivity_Call struct {
	*mock.Call
}

// DeleteActivity is a helper method to define mock.On call
//   - activity track.Activity
func (_e *MockActivityRepository_Expecter) DeleteActivity(activity interface{}) *MockActivityRepository_DeleteActivity_Call {
	return &MockActivityRepository_DeleteActivity_Call{Call: _e.mock.On("DeleteActivity", activity)}
}

func (_c *MockActivityRepository_DeleteActivity_Call) Run(run func(activity track.Activity)) *MockActivityRepository_DeleteActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(track.Activity))
	})
	return _c
}

func (_c *MockActivityRepository_DeleteActivity_Call) Return(_a0 error) *MockActivityRepository_DeleteActivity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockActivityRepository_DeleteActivity_Call) RunAndReturn(run func(track.Activity) error) *MockActivityRepository_DeleteActivity_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllActivities provides a mock function with given fields:
func (_m *MockActivityRepository) GetAllActivities() ([]track.Activity, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllActivities")
	}

	var r0 []track.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]track.Activity, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []track.Activity); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]track.Activity)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockActivityRepository_GetAllActivities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllActivities'
type MockActivityRepository_GetAllActivities_Call struct {
	*mock.Call
}

// GetAllActivities is a helper method to define mock.On call
func (_e *MockActivityRepository_Expecter) GetAllActivities() *MockActivityRepository_GetAllActivities_Call {
	return &MockActivityRepository_GetAllActivities_Call{Call: _e.mock.On("GetAllActivities")}
}

func (_c *MockActivityRepository_GetAllActivities_Call) Run(run func()) *MockActivityRepository_GetAllActivities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockActivityRepository_GetAllActivities_Call) Return(_a0 []track.Activity, _a1 error) *MockActivityRepository_GetAllActivities_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockActivityRepository_GetAllActivities_Call) RunAndReturn(run func() ([]track.Activity, error)) *MockActivityRepository_GetAllActivities_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastActivity provides a mock function with given fields:
func (_m *MockActivityRepository) GetLastActivity() (track.Activity, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLastActivity")
	}

	var r0 track.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func() (track.Activity, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() track.Activity); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(track.Activity)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockActivityRepository_GetLastActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastActivity'
type MockActivityRepository_GetLastActivity_Call struct {
	*mock.Call
}

// GetLastActivity is a helper method to define mock.On call
func (_e *MockActivityRepository_Expecter) GetLastActivity() *MockActivityRepository_GetLastActivity_Call {
	return &MockActivityRepository_GetLastActivity_Call{Call: _e.mock.On("GetLastActivity")}
}

func (_c *MockActivityRepository_GetLastActivity_Call) Run(run func()) *MockActivityRepository_GetLastActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockActivityRepository_GetLastActivity_Call) Return(_a0 track.Activity, _a1 error) *MockActivityRepository_GetLastActivity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockActivityRepository_GetLastActivity_Call) RunAndReturn(run func() (track.Activity, error)) *MockActivityRepository_GetLastActivity_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnsyncedActivities provides a mock function with given fields:
func (_m *MockActivityRepository) GetUnsyncedActivities() ([]track.Activity, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUnsyncedActivities")
	}

	var r0 []track.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]track.Activity, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []track.Activity); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]track.Activity)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockActivityRepository_GetUnsyncedActivities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnsyncedActivities'
type MockActivityRepository_GetUnsyncedActivities_Call struct {
	*mock.Call
}

// GetUnsyncedActivities is a helper method to define mock.On call
func (_e *MockActivityRepository_Expecter) GetUnsyncedActivities() *MockActivityRepository_GetUnsyncedActivities_Call {
	return &MockActivityRepository_GetUnsyncedActivities_Call{Call: _e.mock.On("GetUnsyncedActivities")}
}

func (_c *MockActivityRepository_GetUnsyncedActivities_Call) Run(run func()) *MockActivityRepository_GetUnsyncedActivities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockActivityRepository_GetUnsyncedActivities_Call) Return(_a0 []track.Activity, _a1 error) *MockActivityRepository_GetUnsyncedActivities_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockActivityRepository_GetUnsyncedActivities_Call) RunAndReturn(run func() ([]track.Activity, error)) *MockActivityRepository_GetUnsyncedActivities_Call {
	_c.Call.Return(run)
	return _c
}

// MarkActivityAsSynced provides a mock function with given fields: activity
func (_m *MockActivityRepository) MarkActivityAsSynced(activity track.Activity) error {
	ret := _m.Called(activity)

	if len(ret) == 0 {
		panic("no return value specified for MarkActivityAsSynced")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(track.Activity) error); ok {
		r0 = rf(activity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockActivityRepository_MarkActivityAsSynced_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkActivityAsSynced'
type MockActivityRepository_MarkActivityAsSynced_Call struct {
	*mock.Call
}

// MarkActivityAsSynced is a helper method to define mock.On call
//   - activity track.Activity
func (_e *MockActivityRepository_Expecter) MarkActivityAsSynced(activity interface{}) *MockActivityRepository_MarkActivityAsSynced_Call {
	return &MockActivityRepository_MarkActivityAsSynced_Call{Call: _e.mock.On("MarkActivityAsSynced", activity)}
}

func (_c *MockActivityRepository_MarkActivityAsSynced_Call) Run(run func(activity track.Activity)) *MockActivityRepository_MarkActivityAsSynced_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(track.Activity))
	})
	return _c
}

func (_c *MockActivityRepository_MarkActivityAsSynced_Call) Return(_a0 error) *MockActivityRepository_MarkActivityAsSynced_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockActivityRepository_MarkActivityAsSynced_Call) RunAndReturn(run func(track.Activity) error) *MockActivityRepository_MarkActivityAsSynced_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateActivity provides a mock function with given fields: activity
func (_m *MockActivityRepository) UpdateActivity(activity track.Activity) error {
	ret := _m.Called(activity)

	if len(ret) == 0 {
		panic("no return value specified for UpdateActivity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(track.Activity) error); ok {
		r0 = rf(activity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockActivityRepository_UpdateActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateActivity'
type MockActivityRepository_UpdateActivity_Call struct {
	*mock.Call
}

// UpdateActivity is a helper method to define mock.On call
//   - activity track.Activity
func (_e *MockActivityRepository_Expecter) UpdateActivity(activity interface{}) *MockActivityRepository_UpdateActivity_Call {
	return &MockActivityRepository_UpdateActivity_Call{Call: _e.mock.On("UpdateActivity", activity)}
}

func (_c *MockActivityRepository_UpdateActivity_Call) Run(run func(activity track.Activity)) *MockActivityRepository_UpdateActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(track.Activity))
	})
	return _c
}

func (_c *MockActivityRepository_UpdateActivity_Call) Return(_a0 error) *MockActivityRepository_UpdateActivity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockActivityRepository_UpdateActivity_Call) RunAndReturn(run func(track.Activity) error) *MockActivityRepository_UpdateActivity_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockActivityRepository creates a new instance of MockActivityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActivityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActivityRepository {
	mock := &MockActivityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
