// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockUI is an autogenerated mock type for the UI type
type MockUI struct {
	mock.Mock
}

type MockUI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUI) EXPECT() *MockUI_Expecter {
	return &MockUI_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields:
func (_m *MockUI) Run() {
	_m.Called()
}

// MockUI_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockUI_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *MockUI_Expecter) Run() *MockUI_Run_Call {
	return &MockUI_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *MockUI_Run_Call) Run(run func()) *MockUI_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUI_Run_Call) Return() *MockUI_Run_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUI_Run_Call) RunAndReturn(run func()) *MockUI_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUI creates a new instance of MockUI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUI {
	mock := &MockUI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
