name: dagger
on:
  push:
    branches:
      - main

jobs:
  build:
    name: generate documentation
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: generate architecture documentation
        uses: dagger/dagger-for-github@v5
        with:
          version: "latest"
          verb: call
          args: generate-architecture --source=. export --path=./architecture.pdf
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
