name: dagger

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test dagger call
        uses: dagger/dagger-for-github@v5
        with:
          verb: call
          module: ci
          args: container-echo --string-arg='hello world'
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "0.10.3"
