name: Build binaries

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'

      - name: install dependencies
        run: go get .

      - name: generate files
        run: go generate

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: build binaries
        run: make build

      - name: upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: |
            track
          retention-days: 1
