name: run tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 10

      - name: run tests
        uses: dagger/dagger-for-github@v5
        with:
          version: "latest"
          verb: call
          args: test --source=.
