name: Build binaries

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'

      - name: install dependencies
        run: go get .

      - name: generate files
        run: go generate

      - name: run tests
        run: go test $(go list ./... | grep -v ci)

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: build binaries
        run: make build

      - name: upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: track
          retention-days: 1
